- name: Update git clone
  git:
    repo: ssh://git@github.com/{{ repo_name }}.git
    dest: "{{ repo_folder }}"
    version: "{{ repo_branch }}"
    update: yes

- name: Build project
  command: ./scripts/build.sh
  args:
    chdir: "{{ repo_folder }}"
  environment:
    PATH: /sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin
