linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true

  enable:
    - bodyclose
    - deadcode
    # - errcheck
    - goconst
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - misspell
    - nakedret
    - varcheck
    - gocritic
    # - gocyclo
    # - golint
    # - gomnd
    # - goprintffuncname
    # - ineffassign
    # - interfacer
    # - lll
    # - unconvert 
