language: go
go:
  - 1.13.x

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.4
services:
- docker
env:
  global:
  - CODECOV_TOKEN="8c18c993-fc6e-4706-998b-01ddc7987804"
  - GECKO_HOME=$GOPATH/src/github.com/$TRAVIS_REPO_SLUG/
  - E2E_TEST_HOME=$GOPATH/src/github.com/ava-labs/avalanche-testing/
  - COMMIT=${TRAVIS_COMMIT::8}
  - DOCKERHUB_REPO=avaplatform/gecko
before_install:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then .ci/before_install_linux.sh; fi

install: 
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then DOCKER_BUILDKIT=1 docker build --progress plain -t $DOCKERHUB_REPO:$COMMIT . ; fi

script: 
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then .ci/runscript_osx.sh; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then .ci/runscript_linux.sh; .ci/run_e2e_tests.sh; fi

#Need to push to docker hub only from one build
after_success: 
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then .ci/after_success.sh; fi
