language: go

go:
- 1.15.5

env:
  global:
  - AVALANCHE_HOME=$GOPATH/src/github.com/$TRAVIS_REPO_SLUG/
  - E2E_TEST_HOME=$GOPATH/src/github.com/ava-labs/avalanche-testing/
  - COMMIT=${TRAVIS_COMMIT::8}
  - DOCKERHUB_REPO=avaplatform/avalanchego

jobs:
  include:
  - stage: lint
    os: linux
    dist: bionic
    script:
    - ".ci/lint.sh"

  - stage: build
    os: osx
    osx_image: xcode11.4
    script:
    - ".ci/build_and_test.sh"

  - stage: build
    os: windows
    script:
    - ".ci/build_and_test.sh"
