[package]
name = "rust_bag"
version = "0.1.0"
authors = ["Dan Laine <daniel.laine@avalabs.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
