# Debian 10.x (buster) includes golang 1.11.x.
# The testing repository tracks https://golang.org releases more closely.

- name: Configure default release
  become: true
  copy:
    content: |
      APT::Default-Release "stable";
    dest: /etc/apt/apt.conf.d/99defaultrelease
  tags:
    - golang_base

- name: Add Go repository
  become: true
  apt_repository:
    repo: deb http://deb.debian.org/debian testing main
  tags:
    - golang_base

- name: Install Go
  become: true
  # Apt doesn't support specifying a minimum version (e.g. foo >= 1.0)
  # https://github.com/ansible/ansible/issues/69034
  apt:
    name:
      - "golang-{{ golang_version_min_major }}.{{ golang_version_min_minor }}-go"
    default_release: testing
  tags:
    - golang_base

- name: Query installed packages
  package_facts:
  tags:
    - golang_base

- name: Check minimum Go version
  vars:
    pkg_name: golang-{{ golang_version_min_major }}.{{ golang_version_min_minor }}-go
  assert:
    that:
      - pkg_name in ansible_facts.packages
      - ansible_facts.packages[pkg_name][0].version is version(golang_version_min, '>=')
  tags:
    - golang_base
