- name: Add Go repository
  become: true
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
  tags:
    - golang_base

- name: Install Go
  become: true
  apt:
    name:
      - golang-go
    default_release: buster-backports
  tags:
    - golang_base
