- name: Create AVA daemon group
  become: true
  group:
    name: "{{ ava_daemon_group }}"
    system: true

- name: Create AVA daemon user
  become: true
  user:
    name: "{{ ava_daemon_user }}"
    group: "{{ ava_daemon_group }}"
    home: "{{ ava_daemon_home_dir }}"
    shell: /bin/false
    skeleton: false
    system: true
