[package]
name = "rust-counter"
version = "0.1.0"
authors = ["Dan Laine <daniel.laine@avalabs.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
lazy_static = "1.4.0"

[lib]
crate-type = ["cdylib", "rlib"]