- name: Create shared directories
  become: true
  file:
    path: "{{ item.path }}"
    state: directory
    # This task intentionally leaves the owner, group, & mode unspecified.
    # The intention is to preserve permissions chosen by the Operating System
    # vendor, in the case that e.g. /var/local has been created by them.
    # You might think `mode: preserve` does this, but that is not supported
    # with `state: directory`. ansible-lint erroneously flags this as E208.
    # See: https://github.com/ansible/ansible/issues/71377
  loop:
    - path: "{{ sharedstatedir }}"
    - path: "{{ logdir }}"

- name: Create Avalanche directories
  become: true
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(avalanche_daemon_user) }}"
    group: "{{ item.group | default(avalanche_daemon_group) }}"
    mode: "{{ item.mode }}"
    recurse: "{{ item.recurse | default(omit) }}"
    state: directory
  loop:
    - path: "{{ avalanche_daemon_home_dir }}"
      mode: u=rwX,go=rX
    - path: "{{ avalanche_daemon_db_dir }}"
      mode: u=rwX,go=rX
    - path: "{{ avalanche_daemon_staking_dir }}"
      mode: u=rX,go=
    - path: "{{ avalanche_daemon_log_dir }}"
      mode: u=rwX,go=rX
    - path: "{{ avalanche_daemon_plugin_dir }}"
      owner: root
      group: root
      mode: u=rwX,go=rX
      recurse: true
  loop_control:
    label: "{{ item.path }}"
  notify:
    - Restart Avalanche service

- name: Install Avalanche binary
  become: true
  copy:
    src: "{{ avalanche_binary }}"
    dest: "{{ bindir }}/avalanche"
    remote_src: true
    owner: root
    group: root
    mode: u=rwx,go=rx
  notify:
    - Restart Avalanche service

- name: Install Avalanche plugins
  become: true
  copy:
    src: "{{ item.path }}"
    dest: "{{ avalanche_daemon_plugin_dir }}"
    owner: root
    group: root
    mode: u=rwx,go=rx
    remote_src: true
  loop:
    - path: "{{ repo_folder }}/build/plugins/evm"
  notify:
    - Restart Avalanche service
