
---
- name: Update the network
  connection: ssh
  gather_facts: false
  hosts: all
  vars:
    repo_name: ava-labs/gecko-internal
    repo_branch: platformvm-proposal-accept
  roles:
    - name: ava-stop
    - name: ava-build
    - name: ava-reset
    - name: ava-start
