
---
- name: Update the network
  connection: ssh
  gather_facts: false
  hosts: all
  vars:
    ava_binary: ~/go/src/github.com/ava-labs/gecko/build/ava
    repo_folder: ~/go/src/github.com/ava-labs/gecko
    repo_name: ava-labs/gecko
    repo_branch: master
  roles:
    - name: ava-stop
    - name: ava-build
    - name: ava-reset
    - name: ava-start
