#!/usr/bin/env ansible-playbook
---
- name: Configure Avalanche service
  hosts: avalanche_nodes
  roles:
    - name: golang-base
    - name: gopath
    - name: avalanche-base
    - name: avalanche-build
    - name: avalanche-user
    - name: avalanche-install
    - name: avalanche-upgrade
    - name: avalanche-service
