
---
- name: Update the network
  connection: ssh
  gather_facts: false
  hosts: all
  vars:
    repo_name: ava-labs/gecko
    repo_branch: master
  roles:
    - name: ava-stop
    - name: ava-build
    - name: ava-start
