name: build-amd64-debian-packages

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build-jammy-amd64-package:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
      - run: go version

      - name: build golang from source
        run: |
          git clone https://go.googlesource.com/go goroot
          cd goroot
          git checkout release-branch.go1.20
          echo -n "-" >> VERSION
          git rev-parse HEAD >> VERSION
          cd src
          ./make.bash
          rm -rf /home/runner/go
          cd ..
          cd ..
          mv goroot /home/runner/go

      - run: go version
      - run: go env

      - name: Build the avalanchego binaries
        run: ./scripts/build.sh

      - name: Install aws cli
        run: |
          sudo apt update
          sudo apt -y install awscli

      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create debian package
        run: ./.github/workflows/build-deb-pkg.sh
        env:
          TAG: ${{ env.VERSION }}
          BUCKET: ${{ secrets.BUCKET }}
          ARCH: "amd64"
          RELEASE: "jammy"

  build-focal-amd64-package:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
      - run: go version

      - name: build golang from source
        run: |
          git clone https://go.googlesource.com/go goroot
          cd goroot
          git checkout release-branch.go1.20
          echo -n "-" >> VERSION
          git rev-parse HEAD >> VERSION
          cd src
          ./make.bash
          rm -rf /home/runner/go
          cd ..
          cd ..
          mv goroot /home/runner/go

      - run: go version
      - run: go env

      - name: Build the avalanchego binaries
        run: ./scripts/build.sh

      - name: Install aws cli
        run: |
          sudo apt update
          sudo apt -y install awscli

      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create debian package
        run: ./.github/workflows/build-deb-pkg.sh
        env:
          TAG: ${{ env.VERSION }}
          BUCKET: ${{ secrets.BUCKET }}
          ARCH: "amd64"
          RELEASE: "focal"
