name: build-amd64-source

on:
  push:

jobs:
  build-jammy-amd64-package:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
      - name: build golang from source
        run: |
          sudo apt update
          sudo apt -y install git
          git clone https://go.googlesource.com/go goroot
          cd goroot
          git checkout release-branch.go1.20
          cd src
          ./all.bash

      - run: go version

      - name: Build the avalanchego binaries
        run: ./scripts/build.sh
