name: build-amd64-source

on:
  push:

jobs:
  build-amd64-package-from-source:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
      - name: build golang from source
        run: |
          sudo apt update
          sudo apt -y install git
          git clone https://go.googlesource.com/go goroot
          cd goroot
          git checkout release-branch.go1.20
          cd src
          ./make.bash
          rm -rf /home/runner/go
          cd ..
          cd ..
          mv goroot /home/runner/go

      - run: go version
      - run: go env

      - name: Build the avalanchego binaries
        run: ./scripts/build.sh
