name: Build + Unit Tests

on:
  push:

jobs:
  run_build_unit_tests:
    name: build_unit_test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0, ubuntu-latest, windows-latest, [self-hosted, linux, ARM64, bionic]]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
      - name: build_test
        shell: bash
        run: .github/workflows/build_and_test.sh
