name: Deploy to Integration

on:
  push:
    branches:
      - CD

jobs:
  deploy-to-integration:
    runs-on: [self-hosted, linux, deploy]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: master

    - name: Checkout devops repo
      uses: actions/checkout@v2
      with: 
        repository: ava-labs/devops
        token: ${{ secrets.AVALANCHE_PAT }}
  
    - name: Run Ansible
      run: |
        ansible-playbook -i scripts/ansible/testnet/inventory/integration-validators.yml -u avalanche scripts/ansible/testnet/healthy.yml
