name: Deploy to Integration

on:
  push:
    branches:
      - CD

jobs:
  deploy-to-integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: master

    - name: Checkout devops repo
      uses: actions/checkout@v2
      with: 
        repository: ava-labs/devops
        token: ${{ secrets.AVALANCHE_PAT }}
