---
- hosts: all 
  gather_facts: no 
  remote_user: ubuntu
  
  tasks:
    - name: create releases directories 
      file:
        path: /home/ubuntu/releases
        state: directory
        owner: ubuntu 
        group: ubuntu 
        mode: '0755'

    - name: upload latest .deb build
      s3:
        bucket: {{ BUCKET }}
        object: /linux/deb/{{ DEB_FILE }}
        dest: /home/ubuntu/releases
        mode: get

    - name: install deb file 
      become: yes 
      command: dpkg -i /home/ubuntu/releases/{{ DEB_FILE }}

    - name: copy systemd script
      become: yes
      copy:
        src: tmpl/avalanchego.service
        dest: /etc/systemd/system/avalanchego.service
        owner: root
        group: root
        mode: 0755

    - name: create conf dir 
      become: yes
      file:
        path: /etc/avalanchego
        state: directory
        owner: root 
        group: root
        mode: '0755'

    - name: copy config file 
      become: yes
      copy:
        src: tmpl/conf.json
        dest: /etc/avalanchego/conf.json
        owner: root
        group: root
        mode: 0755
      notify:
        - Restart Avalanche service
        
  handlers:
    - name: Reload systemd
      become: true
      systemd:
        daemon_reload: yes 
 
    - name: Restart Avalanche service
      become: true
      service:
        name: "avalanche"
        state: restarted
