name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - master
      - dev

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Publish image to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASS: ${{ secrets.docker_pass }}
          DOCKER_REPO: ${{ secrets.docker_repo }}
        run: .github/workflows/publish_image.sh
