name: Test + build Image

on:
  push:
    branches:
      - kurtosis_upgrade

jobs:
  run_lint:
    name: lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: .

  run_build_tests:
    needs: run_lint
    name: build_tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: build_test
        run: .github/workflows/build_and_test.sh


  run_e2e_tests_plus_publish_image:
    needs: run_build_tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Kurtosis Tests
        env:
          KURTOSIS_CLIENT_ID: ${{ secrets.kurtosis_client_id }}
          KURTOSIS_CLIENT_SECRET: ${{ secrets.kurtosis_client_secret }}
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASS: ${{ secrets.docker_pass }}
        run: .github/workflows/run_e2e_tests.sh

      - name: Publish image to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASS: ${{ secrets.docker_pass }}
        run: .github/workflows/publish_image.sh
